### ISSUE TITLE
Crashing on compare tool

### ISSUE THREAD

**Issue by xmha97** [T8RIN/ImageResizer#125]
I have updated the app now.
I noticed that the comparison tool is broken!

https://user-images.githubusercontent.com/23485114/229004424-2e981034-cb2d-4323-8721-d394be0c798b.mp4

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1028204662, result=-1, data=Intent { flg=0x41 clip={image/* video/* 2 items: {U(content)} {U(content)}} }} to activity {ru.tech.imageresizershrinker/ru.tech.imageresizershrinker.main_screen.MainActivity}: java.lang.SecurityException: No persistable permission grants found for UID 12321 and Uri content://media/...
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1028204662, result=-1, data=Intent { flg=0x41 clip={image/* video/* 2 items: {U(content)} {U(content)}} }} to activity {ru.tech.imageresizershrinker/ru.tech.imageresizershrinker.main_screen.MainActivity}: java.lang.SecurityException: No persistable permission grants found for UID 12321 and Uri content://media/...
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5493)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5532)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8143)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.SecurityException: No persistable permission grants found for UID 12321 and Uri content://media/...
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IUriGrantsManager$Stub$Proxy.takePersistableUriPermission(IUriGrantsManager.java:249)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:2936)
	at s8.a.q(Unknown Source:15)
	at s8.a.h(SourceFile:11)
	at a8.a$m.e0(SourceFile:49)
	at a.b.a(Unknown Source:8)
	at androidx.activity.result.d.a(SourceFile:45)
	at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
	at androidx.fragment.app.j.onActivityResult(Unknown Source:5)
	at android.app.Activity.dispatchActivityResult(Activity.java:8893)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5486)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.takePersistableUriPermission(UriGrantsManagerService.java:381)
	at android.app.IUriGrantsManager$Stub.onTransact(IUriGrantsManager.java:139)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)
```

**Comment by T8RIN** [comment]
That is because of "fix" in #100 i will revert it

**Comment by T8RIN** [comment]
I can't release new version now, so if it necessary for you, you can use unsigned apk from actions page for now👀

**Comment by xmha97** [comment]
Ok
