### ISSUE TITLE
Crash on Telegram link

### ISSUE THREAD

**Issue by shuvashish76** [T8RIN/ImageResizer#127]
Crash logs:
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://t.me/... pkg=org.telegram.messenger }
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://t.me/... pkg=org.telegram.messenger }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2181)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1812)
	at android.app.Activity.startActivityForResult(Activity.java:5506)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivityForResult(Activity.java:5464)
	at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
	at android.app.Activity.startActivity(Activity.java:5854)
	at android.app.Activity.startActivity(Activity.java:5807)
	at l8.b3.C(SourceFile:43)
	at p.a0$b.e0(SourceFile:17)
	at q.j1$a.k(SourceFile:134)
	at h6.a.v(Unknown Source:8)
	at a0.g.F(Unknown Source:77)
	at z6.i.r(SourceFile:129)
	at z6.i.C(SourceFile:44)
	at z6.i.v(SourceFile:17)
	at k1.d0.J(SourceFile:51)
	at k1.d0.E(Unknown Source:8)
	at p1.c.s(Unknown Source:13)
	at k1.i.e(SourceFile:85)
	at k1.i.e(SourceFile:71)
	at k1.i.e(SourceFile:71)
	at k1.j.e(SourceFile:26)
	at k1.u.a(SourceFile:183)
	at androidx.compose.ui.platform.AndroidComposeView.O(SourceFile:78)
	at androidx.compose.ui.platform.AndroidComposeView.E(SourceFile:249)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:88)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:535)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1925)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:864)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:493)
	at android.view.View.dispatchPointerEvent(View.java:14884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6598)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6399)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5877)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5934)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5900)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6065)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5908)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6122)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5881)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5934)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5900)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5908)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5881)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8895)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8811)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8780)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9031)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:342)
	at android.os.Looper.loopOnce(Looper.java:182)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
	Suppressed: n4.e: [androidx.compose.ui.platform.f2@48d7a5f, k0.e@3cac, o1{Cancelling}@b9e6d75, z0@54c710a]

```
App version : 1.9.7 (43)

**Comment by T8RIN** [comment]
You have no telegram installed, i suggest? I will fix this later

**Comment by shuvashish76** [comment]
I do, [Forkgram](https://www.f-droid.org/packages/org.forkgram.messenger/)
There are multiple Telegram clients e.g. [Telegram FOSS](https://www.f-droid.org/packages/org.telegram.messenger/), [Nekogram X](https://www.f-droid.org/packages/nekox.messenger/), [Telegram X](https://github.com/TGX-Android/Telegram-X/) etc... why redirect to TG official client?

**Comment by T8RIN** [comment]
Oh, got it, i will remove setpackage for the intent

**Comment by T8RIN** [comment]
Done 👀
