### ISSUE TITLE
Stable crash, last current version:

### ISSUE THREAD

**Issue by Perlover** [T8RIN/ImageResizer#167]
java.lang.NullPointerException
java.lang.NullPointerException
	at p6.y.E1(SourceFile:181)
	at b8.s.a(SourceFile:21)
	at b8.s.R(SourceFile:11)
	at i8.b.g(SourceFile:131)
	at x5.a.v(Unknown Source:8)
	at p6.e0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: i4.e: [p1{Cancelling}@1bed89, Dispatchers.Main.immediate]

**Comment by Perlover** [comment]
This original image

You can try to test:

https://photos.app.goo.gl/1aZ7EzhxxeWaCog87

**Comment by T8RIN** [comment]
How can i reproduce it?

**Comment by phiresky** [comment]
I have the same issue (I think).

```
java.lang.NullPointerException
java.lang.NullPointerException
	at p6.y.y1(SourceFile:181)
	at b8.s.a(SourceFile:54)
	at b8.s.R(SourceFile:38)
	at n7.d.g(SourceFile:237)
	at x5.a.v(Unknown Source:8)
	at p6.e0.run(Unknown Source:104)
	at kotlinx.coroutines.internal.e.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.i.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(SourceFile:77)
	Suppressed: i4.e: [p1{Cancelling}@ea371a1, Dispatchers.Main.immediate]
```

It started happening when I selected a custom save directory on SD card:
![Screenshot_20230504-111255_Trebuchet](https://user-images.githubusercontent.com/2303841/236175916-4834db01-1230-4870-b526-031bd4eb6e57.png)

It's been happening for all of the past few versions including the current release (2.0.0)

**Comment by T8RIN** [comment]
Which android version did you have? And when it is happening

**Comment by phiresky** [comment]
It happens when pressing the "save" button both for single and batch resize (so the app is Jon functional).

When I switch the output dir back to the default it stops happening.

**Comment by phiresky** [comment]
One more info: After setting the custom directory immediately it still works. It only stops working after closing the app and opening it again.

**Comment by phiresky** [comment]
Android Version 13

**Comment by T8RIN** [comment]
What if you use a custom folder but not on the sd card, is it happening?

**Comment by phiresky** [comment]
Yes, still happens.

**Comment by T8RIN** [comment]
checked on Android 11, bug is happening, i will try to find the solution soon :(
