### ISSUE TITLE
App crashes on editing Width/Height manually

### ISSUE THREAD

**Issue by Runner86** [T8RIN/ImageResizer#229]
Test feature: Editing Width/Height manually
Tested on: Android 12, Snapdragon 665

Use case: select one or more images for resize, choose Resize type Flexible or Ratio and edit Width/Height manually

Observed result: randomly the app crashes - see log:

java.lang.IllegalStateException: No borders present
java.lang.IllegalStateException: No borders present
	at j8.g0.m(SourceFile:74)
	at x5.h.getValue(Unknown Source:20)
	at l0.c1.getValue(Unknown Source:2)
	at v6.y.b2(SourceFile:36)
	at l0.w.k(Unknown Source:9)
	at u8.p0.a(SourceFile:422)
	at n8.b.Z(SourceFile:359)
	at s0.d.e(SourceFile:51)
	at s0.d.Z(Unknown Source:8)
	at d8.b.V(SourceFile:289)
	at s0.d.d(SourceFile:51)
	at s0.d.V(Unknown Source:8)
	at n.k.Z(SourceFile:446)
	at s0.d.e(SourceFile:51)
	at s0.d.Z(Unknown Source:8)
	at a0.b1.m(SourceFile:1823)
	at a0.b1.o(SourceFile:289)
	at n.l.a(SourceFile:288)
	at n.l.d0(SourceFile:29)
	at s0.d.d0(SourceFile:59)
	at v6.y.b(SourceFile:1056)
	at v6.y.a(SourceFile:329)
	at u8.p0.b(SourceFile:226)
	at v.z.a(SourceFile:915)
	at v.z.d0(SourceFile:137)
	at l0.w.N(SourceFile:283)
	at l0.w.Y(SourceFile:58)
	at l0.w.p(SourceFile:167)
	at l0.w.M(SourceFile:36)
	at l0.c0.w(SourceFile:19)
	at l0.j2.q(SourceFile:98)
	at l0.g2.k0(SourceFile:361)
	at androidx.compose.ui.platform.w0.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.u0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1118)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:854)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
	Suppressed: m4.e: [l0.p1@9117cf9, androidx.compose.ui.platform.v1@21c443e, q1{Cancelling}@8c8229f, v0@dbd5fec]

**Comment by Runner86** [comment]
remark: Tests had been done with Version 2.0.4 (60)

**Comment by T8RIN** [comment]
I will close the issue if it is solved 👀
