### ISSUE TITLE
Just upgraded to new version and won't open

### ISSUE THREAD

**Issue by J43git** [T8RIN/ImageResizer#239]
I installed the new update, as you do, and when it finished I open it and it leads to a neverending wave of splash screens.

**Comment by T8RIN** [comment]
Can you try to clean all data? :(

**Comment by T8RIN** [comment]
Have no idea what it is, try a fresh install then, maybe just the package installed badly :(

**Comment by uli-on** [comment]
I had that, too, and with the scoop app could  catch a stack trace. And, yes, deleting all app data helped.

```
FATAL EXCEPTION: main
Process: ru.tech.imageresizershrinker, PID: 31130
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Float
	at k8.a.m(SourceFile:249)
	at k8.a.Y(SourceFile:13)
	at n3.g.m(SourceFile:53)
	at n3.g.Y(SourceFile:13)
	at n3.b.m(SourceFile:33)
	at n3.b.Y(SourceFile:13)
	at n3.b.m(SourceFile:33)
	at n3.b.Y(SourceFile:13)
	at j3.f0.m(Unknown Source:30)
	at g6.a.r(Unknown Source:8)
	at z6.c0.run(Unknown Source:109)
	at z6.m0.V(SourceFile:159)
	at f3.b.c0(SourceFile:99)
	at f3.b.d0(Unknown Source:2)
	at ru.tech.imageresizershrinker.crash_screen.viewModel.CrashViewModel.<init>(SourceFile:61)
	at a8.f.get(Unknown Source:39)
	at v5.c.b(SourceFile:106)
	at v5.e.b(Unknown Source:14)
	at f.c.g(SourceFile:73)
	at f.c.f(Unknown Source:12)
	at androidx.lifecycle.o0.getValue(SourceFile:52)
	at ru.tech.imageresizershrinker.crash_screen.CrashActivity.E(Unknown Source:2)
	at r.i0.b(SourceFile:689)
	at r.i0.Y(SourceFile:140)
	at v0.d.Y(SourceFile:59)
	at androidx.compose.ui.platform.i1.a(SourceFile:25)
	at u.s1.a(SourceFile:1415)
	at u.s1.Y(SourceFile:256)
	at v0.d.Y(SourceFile:59)
	at k5.b.f(SourceFile:182)
	at androidx.compose.ui.platform.k1.a(SourceFile:346)
	at x.n0.a(SourceFile:239)
	at x.n0.Y(SourceFile:66)
	at v0.d.Y(SourceFile:59)
	at k5.b.f(SourceFile:182)
	at androidx.compose.ui.platform.q0.a(SourceFile:540)
	at androidx.compose.ui.platform.i3.a(SourceFile:34)
	at androidx.compose.ui.platform.i3.Y(SourceFile:17)
	at v0.d.Y(SourceFile:59)
	at k5.b.f(SourceFile:182)
	at androidx.compose.ui.platform.i3.a(SourceFile:179)
	at androidx.compose.ui.platform.i3.Y(SourceFile:29)
	at v0.d.Y(SourceFile:59)
	at k5.b.b1(Unknown Source:19)
	at o0.x.q(SourceFile:131)
	at o0.x.i(Unknown Source:13)
	at o0.c0.p(SourceFile:19)
	at o0.g2.a(SourceFile:46)
	at o0.c0.g(Unknown Source:10)
	at androidx.compose.ui.platform.j3.h0(SourceFile:109)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:11)
	at androidx.compose.ui.platform.WrappedComposition.g(Unknown Source:13)
	at androidx.compose.ui.platform.WrappedComposition.e(Unknown Source:18)
	at androidx.lifecycle.v.a(SourceFile:23)
	at androidx.lifecycle.w.a(SourceFile:141)
	at androidx.compose.ui.platform.j3.h0(SourceFile:73)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:114)
	at android.view.View.dispatchAttachedToWindow(View.java:20109)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2050)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7772)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by T8RIN** [comment]
Got it, i've changed some key value types inside the saved settings, so that's because this occurred :(

**Comment by nursoda** [comment]
Why do I see 2.0.5 in Aurora but not in F-Droid?

**Comment by uli-on** [comment]
Have you added the Izzy repo to your fdroid app?

**Comment by J43git** [comment]
> Can you try to clean all data? :(

It works! Thank you!

**Comment by T8RIN** [comment]
> Why do I see 2.0.5 in Aurora (including Play Store Repo) but not in F-Droid (Default) – have you pulled 2.0.5 from F-Droid but not from Play Store? Or, didn't you release 2.0.5 on F-Droid yet?

F-droid builds releases automatically, so this takes time(from one to five days)
