### ISSUE TITLE
Crashed when batch processing two images

### ISSUE THREAD

**Issue by GET100PERCENT** [T8RIN/ImageResizer#27]
Here is the error code:
java.lang.OutOfMemoryError: Failed to allocate a 132483960 byte allocation with 16773152 free bytes and 94MB until OOM
java.lang.OutOfMemoryError: Failed to allocate a 132483960 byte allocation with 16773152 free bytes and 94MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:726)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:702)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:740)
	at f6.a.h(SourceFile)
	at q5.e.j(SourceFile:45)
	at e4.a.p(SourceFile)
	at u4.h0.run(SourceFile)
	at kotlinx.coroutines.internal.e.run(SourceFile)
	at kotlinx.coroutines.scheduling.j.run(SourceFile)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
	Suppressed: u4.f0: [k1{Cancelling}@74a284, Dispatchers.Main.immediate]

**Comment by GET100PERCENT** [comment]
Similar error when opening one of the two images:
java.lang.OutOfMemoryError: Failed to allocate a 132483960 byte allocation with 16773912 free bytes and 93MB until OOM
java.lang.OutOfMemoryError: Failed to allocate a 132483960 byte allocation with 16773912 free bytes and 93MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:726)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:702)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:740)
	at f6.a.h(SourceFile)
	at d6.c.j(SourceFile:45)
	at e4.a.p(SourceFile)
	at u4.h0.run(SourceFile)
	at kotlinx.coroutines.internal.e.run(SourceFile)
	at kotlinx.coroutines.scheduling.j.run(SourceFile)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
	Suppressed: u4.f0: [k1{Cancelling}@b068cfd, Dispatchers.Main.immediate]
![Screenshot_20230303-125456](https://user-images.githubusercontent.com/116144024/222657780-d91470d1-f1b7-408f-9fad-0707878046d9.jpg)

**Comment by T8RIN** [comment]
This only means that you trying to resize too large images for your device, can you send them here?

**Comment by GET100PERCENT** [comment]
No, i can't share the photos here.
But the photos are 4.7 mb and 4.9 mb only.
My device memory is 2gb and operating system is android 7.1.1.
When it crashed i used the below app
https://play.google.com/store/apps/details?id=com.simplemobilephotoresizer
And in the app resize took place with no crashes.

**Comment by T8RIN** [comment]
> No, i can't share the photos here.
> But the photos are 4.7 mb and 4.9 mb only.
> My device memory is 2gb and operating system is android 7.1.1.
> When it crashed i used the below app
> https://play.google.com/store/apps/details?id=com.simplemobilephotoresizer
> And in the app resize took place with no crashes.

Which resolution they are?

**Comment by T8RIN** [comment]
132483960 is a 132 mb sized image, this is too large

**Comment by GET100PERCENT** [comment]
The details of the images are here:
![Screenshot_20230303-192105](https://user-images.githubusercontent.com/116144024/222737385-fb85b289-3c17-4190-bbdf-17db4f2aaac4.jpg)

**Comment by T8RIN** [comment]
Have no idea, saving should work correctly, I'm fine even with 8k images :(

**Comment by GET100PERCENT** [comment]
Oh then, the problem may be specific to my device.

**Comment by T8RIN** [comment]
Can we close the issue?

**Comment by GET100PERCENT** [comment]
> Can we close the issue?

Yes, you can.

**Comment by GET100PERCENT** [comment]
Yes you can close it.

**Comment by T8RIN** [comment]
Ok
